import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SocketProvider } from "@/providers/SocketProvider";
import { AuthProvider } from "@/context/Authcontext";
import { WorkspaceProvider } from "@/context/Workspacecontext";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Slack",
    description: "Generated by Bladmir",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <head>
                {/* Favicon link */}
                <link rel="icon" href="/slack.svg" />
            </head>
            <body className="min-h-full flex flex-col">
                <SocketProvider>
                    <AuthProvider>
                        <WorkspaceProvider>
                            {children}
                        </WorkspaceProvider>
                    </AuthProvider>
                </SocketProvider>
            </body>
        </html>
    );
}
